[project]
name = "applied-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydealer>=1.4.0",
    "tqdm>=4.67.1",
]
